package com.company;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

public class OrmDB {
    SQLConnect sql = new SQLConnect();
    String dbname = "sia_testex";
    public void createDB() throws  SQLException{
        System.out.println("Drop DB "+dbname+" if exists and create DB "+dbname+"...");

        ResultSet res = sql.stat.executeQuery("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = '"+dbname+"' AND table_name = '"+dbname+"';");
        if(res.next()){
            sql.stat.execute("SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = '"+dbname+"';");
        }

        sql.stat.execute("DROP DATABASE IF EXISTS "+dbname+";");
        sql.stat.execute("CREATE DATABASE "+dbname+";");


       SQLConnect.dbname = "sia_testex";
       System.out.println("Reconnect to "+ SQLConnect.dbname +"...");
        sql.stat.execute("SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = '"+dbname+"';");
       sql.close();

        sql = new SQLConnect();

    }
    public void createTable() throws SQLException {
        System.out.println("Create Table in DB if it not exists...");
        sql.stat.execute("CREATE TABLE IF NOT EXISTS bubble_sort_tab " +
                "(id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
                "id_sort integer NOT NULL," +
                "value integer NOT NULL)");
    }
    public void saveSortRes(String[] nums) throws SQLException {
        System.out.println("Save Sort Result in DB...");
        ResultSet resultSet = sql.stat.executeQuery("SELECT MAX(id_sort) FROM bubble_sort_tab;");
        resultSet.next();
        int id_sort = resultSet.getInt(1)+1;
        resultSet.close();
        System.out.println(nums[0]);
        for(String num:nums){
            sql.stat.execute("INSERT INTO bubble_sort_tab (id_sort,value) VALUES("+id_sort+","+num+");");
        }
    }
    public ArrayList<Integer> readSortRes(String id_sort) throws SQLException {
        ArrayList<Integer> numbers = new ArrayList<>();
        System.out.println("Read Sort Result in DB...");
        ResultSet resultSet = sql.stat.executeQuery("SELECT value FROM bubble_sort_tab WHERE id_sort="+id_sort+";");
        while(resultSet.next()){
            numbers.add(resultSet.getInt(1));
        }
        resultSet.close();
        return numbers;
    }
}
